name: LinkedIn WebScraper

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

permissions:
  contents: write  # Grant write permission to contents

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Safety timeout since scraper.py has an infinite loop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager bs4 python-dotenv twilio

      - name: Run LinkedIn WebScraper
        env:
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          YOUR_PHONE_NUMBER: ${{ secrets.YOUR_PHONE_NUMBER }}
          COOKIES_B64: ${{ secrets.COOKIES_B64 }}
        run: python scraper.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add job_cache.json
          git diff --cached --quiet || git commit -m "Update job_cache.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
